name: 'Attach a QA URL to an asana ticket'
description: 'Check the pull request description for specific Asana task URLs and add the pull request as an attachment to those tasks'
author: Daniele.gili@crowdhouse.ch
branding:
  icon: circle
  color: green
inputs:
  asana-secret:
    description: 'The Asana secret for the action.'
    required: true
    default: ''
outputs:
  status:
    description: 'status'
runs:
  using: 'node16'
  main: 'dist/index.js'
