on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  qa_url:
    if: github.actor != 'dependabot[bot]' && !github.event.pull_request.draft
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Link QA url to Asana
        uses: crowdhouse/asana-qa-url@v1.0
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
